[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SANITY_DATASET,SANITY_STUDIO_SANITY_DATASET,NEXT_PUBLIC_SANITY_DATASET,SANITY_PROJECT_ID,SANITY_STUDIO_SANITY_PROJECT_ID,NEXT_PUBLIC_SANITY_PROJECT_ID,SANITY_STUDIO_SANITY_API_VERSION"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache"
